env:
  global:
    secure: "EoeC+md+GSazE5Kl7VzPg8IJo2yG+zGabUXe3HMwGvwphBrfjQwViyF/2Pdl0fxaUQJFFeBKTVjLUCeMmrZsFfjLSgrtqVERMyiKUX2E/ttnBND41ixx1QjDGeeYSQd34o2FE6/tFVJvKoUIpM/1ESGA0yUoJHXdOMkD1FsMwDRr+7GeruejJn4LIWLtgq1NafuPWbwKav1reWr7UluAm1uvU/P6hs7dIbEYyy9ZVmcQTjhp2qmk2G0GMidqsqwftDESvt/nkMTRjJfSh/uJVXULMxWxR8nZEb3P3UnKoDKrvXHN8yLrFubI0nQlkBoullR6LgpJsuwJtPEIsAWWV3Ychj2UUjhopvJLWSr9hk/mnjAkYv0bkK3jWcpUG5ZstiiY673NESu0y7MgZie0lUG+xEWtWEvdp2rN6tMBFWqyI1Bp4/ZPWm0tTU36QrDMKZYmU1UWCDbWA5csftuVD+RJgqZ2AmI6Hz51PGPOcKdaTFTthchz4Lz5nO5aJA389F52Z81AsODxNLUeGZWyuetS9Z4il2NmcAo4qqfH3Vkxga2cHe3llfprlbVxlCaeW1Z0ValGs/osmHn6ypFU6HO5wtLfypfcCArrYZkQDv5FVgStadB568X2lael3KaYwufOkOL1bNzo7Bg9Gfi01rm/4wKyUPjsk1vDHzR0d6s="
language: java
jdk: openjdk7
before_install:
  - pip install --user codecov
install:
  - git config --global user.email "travis@sw4j.org"
  - git config --global user.name "travis-ci"
script: mvn clean install
after_success:
  - codecov
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -Dscmpublish.skipCheckin=true post-site scm-publish:publish-scm || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd target/scmpublish-checkout || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git commit -a -m "Automatic created documentation" || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git push -fq https://${GH_TOKEN}@github.com/sw4j-org/tool-jpa-processor.git gh-pages:gh-pages || false'
